{
 "title": "Evidently Data Drift Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "dataset_name", "query": { "query": "label_values(dataset_name)" } }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Evidently Data Drift Monitoring\n\n  This dataset is provided by NYC Taxi and Limousine Commission (TLC) for preds trip duration. \n\n\n\n\n"
   }
  },
  {
   "title": "ML Model in Production:",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, max(last_over_time(evidently_model_version_info[1m])) by (model_version))\n\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "General information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "NYC Taxi Dataset Drift",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "evidently:data_drift:dataset_drift{}",
     "legendFormat": "dataset drift"
    }
   ]
  },
  {
   "title": "Share of drifted features",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "evidently:data_drift:share_drifted_features{}",
     "legendFormat": "share"
    }
   ]
  },
  {
   "title": "Nº of drifted features",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "evidently:data_drift:n_drifted_features{}",
     "legendFormat": "Drifted"
    }
   ]
  },
  {
   "title": "Nº of features",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(evidently:data_drift:value{})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Detailed information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Feature Drift Score",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 21 },
   "targets": [
    { "expr": "evidently:data_drift:value{}", "legendFormat": "{{feature}}" },
    {
     "expr": "evidently:reference_dataset_hash",
     "legendFormat": "reference_hash"
    }
   ]
  }
 ]
}