import os

EVIDENTLY_SERVICE_ADDRESS = os.getenv("EVIDENTLY_SERVICE", "http://127.0.0.1:8000")

MONGODB_ADDRESS = os.getenv("MONGODB_ADDRESS", "mongodb://127.0.0.1:27017")


print(EVIDENTLY_SERVICE_ADDRESS)

print(MONGODB_ADDRESS)