def setup():
    print("=" * 60)
    print("                 MLOps Workflow Setup                  ")
    print("=" * 60)
    print("            Experiment Tracking - Mlflow"               )
    print("-" * 60)
    print(f"{'Tracking Server:':<20} {'Yes, Local Server.'}")
    print(f"{'Backend Store:':<20} {'Azure PostgreSQL.'}")
    print(f"{'Artifacts Store:':<20} {'Azure Blob Storage.'}")
    print("=" * 60)
    print("      Workflow Orchestration Engine - Prefect"          )
    print("-" * 60)    
    print(f"{'Workflow Orchestration Server:':<2} {'Yes, Remote Server (Azure Virtual Machines).'}")
    print("=" * 60)
